### ISSUE TITLE
Feature Request: Integration with Firestore

### ISSUE THREAD

**Issue by qrew** [FirebaseExtended/firepad#294]
Cloud Firestore is Firebase's new flagship database that features richer, faster queries and scales better than the Realtime Database.

 - Google Realtime API [will be shut down in 2019](https://developers.google.com/google-apps/realtime/deprecation) and devs are suggested to [migrate to Cloud Firestore](https://developers.google.com/google-apps/realtime/migration). 

Firepad integration with Firestore  could provide the conflict-resolution solution and operation transformation for Firestore

**Comment by vincentwoo** [comment]
I haven't heard anything about RTDB being sunset. Is that true? Can you link to something?

**Comment by qrew** [comment]
Sure, there definitely should be links. I've updated the request.
No, not the RTDB, but RT API

**Comment by nikmartin** [comment]
This project has nothing to do with the Google Real Time API, so you cane safely close this

**Comment by qrew** [comment]
Yes, Firepad doesn't depend on Google Real Time API. Reference to it was to emphasise that Cloud Firestore is presented as better option for new projects.

**Comment by fbacker** [comment]
Starting a new project and would also like to see firestore as db if possible.

**Comment by JamieCorkhill** [comment]
As per #283 are there any plans for a migration to Firestore at this time?

Thank you.

**Comment by samtstern** [comment]
@JamieCorkhill there are no plans to integrate with Cloud Firestore in firepad.  I'm actually going to close the issue because I don't want to inspire any false hope.

Realtime Database and Cloud Firestore are both great databases with different strengths.  For this use case, Realtime Database is likely to be the right choice because it's very good at handling small "hot" data sets that update frequently.  You certainly *could* build firepad on Cloud Firestore but right now I don't see a strong reason to do so.  If anyone in the community gives it a try please let me know, I'd love to check out the results!

**Comment by JamieCorkhill** [comment]
@samtstern Thanks.
